version: '3.9'

services:
  # Database PostgreSQL
  moneydashboard_postgres_db:
    container_name: moneydashboard_postgres_db
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=moneydashboard
    ports:
      - 5432:5432
    volumes:
      - moneydashboard_postgres_data:/var/lib/postgresql/data
    networks:
      - back

  # Backend Ktor
  moneydashboard_backend:
    container_name: moneydashboard_backend
    build:
      context: ./BE
    ports:
      - 8080:8080
    depends_on:
      - moneydashboard_postgres_db
    networks:
      - back

  # Krakend
  moneydashboard_krakend:
    container_name: moneydashboard_krakend
    build:
      context: ./krakend
    ports:
      - 8081:8080
    depends_on:
      - moneydashboard_backend
    networks:
      - back

  # Frontend Angular
  #  moneydashboard_frontend:
  #    container_name: moneydashboard_frontend
  #    build:
  #      context: ./FE
  #    ports:
  #      - 80:80
  #    depends_on:
  #      - moneydashboard_krakend
  #    networks:
  #      - back

volumes:
  moneydashboard_postgres_data:

networks:
  back: