# Usa l'immagine ufficiale di Node.js
FROM node:18

# Crea e imposta la directory di lavoro all'interno del container
WORKDIR /usr/src/app

# Copia i file di configurazione di Angular (package.json e package-lock.json)
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Copia solo i file di configurazione principali e non il codice (sarà montato come volume in Docker Compose)
COPY angular.json ./
COPY tsconfig.json ./

# Espone la porta per il live server Angular
EXPOSE 4200

# Comando di default: avvia il server di sviluppo Angular
CMD ["npm", "start",]

