# Usa l'immagine ufficiale di Node.js
FROM node:18

# Crea e imposta la directory di lavoro all'interno del container
WORKDIR /usr/src/app

# Copia i file di configurazione di Angular (package.json e package-lock.json)
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Copia tutto il codice sorgente Angular (sarà sovrascritto dal volume in Docker Compose)
COPY . .

# Espone la porta per il live server Angular
EXPOSE 4200

# Comando di default: avvia il server di sviluppo con live reload
CMD ["npm", "start"]
