ktor:
    application:
        modules:
            - mft.dev.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "$URL:jdbc:postgresql://localhost:5432/money_dashboard"
  user: "$USERNAME:postgres"
  password: "$PASSWORD:postgres"
  driver: org.postgresql.Driver