# Usare un'immagine di Node.js come base
FROM node:14

# Impostare la directory di lavoro
WORKDIR /usr/src

# Copiare package.json e package-lock.json
COPY package*.json ./

# Installare le dipendenze
RUN npm install

# Installare nodemon globalmente
RUN npm install -g nodemon

# Copiare tutto il resto del codice sorgente
COPY . .

# Esporre la porta che il server utilizzerà
EXPOSE 3000

# Impostare il comando di default per utilizzare nodemon
CMD ["nodemon", "dist/index.js"]
