# Usare un'immagine di Node.js come base
FROM node:14

# Impostare la directory di lavoro
WORKDIR /usr/src

# Copiare package.json e package-lock.json
COPY package*.json ./

# Installare le dipendenze
RUN npm install

# Copiare tutto il resto del codice sorgente
COPY . .

# Compilare TypeScript
RUN npm install -g typescript

#RUN npm i nodemon

# Esporre la porta che il server utilizzerà
EXPOSE 3000

# Comando di avvio (specificato anche nel docker-compose.yml)
CMD ["node", "dist/index.js"]
